<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Zafiro.MasterSystem.Debug.Emulator/Zafiro.MasterSystem.Debug.Emulator.csproj" />
  </ItemGroup>
</Project>
